// ============================================
// POWERPOINT PRESENTATION GENERATOR
// Exports AI breakdown and assessment to PPTX
// ============================================

import PptxGenJS from 'pptxgenjs';
import { AIBreakdownResponse } from '@/types/breakdown';
import { AssessmentOutput } from '@/types';

// Color scheme
const COLORS = {
  black: '1A1A1A',
  cream: 'F5F0E6',
  white: 'FFFFFF',
  darkGray: '333333',
  lightGray: 'F5F5F5',
  gold: 'C9A962',
  green: '4A7C4E',
  amber: 'D48C2E',
  red: 'C44D4D',
  blue: '3B82F6',
};

interface PresentationOptions {
  projectName: string;
  breakdown: AIBreakdownResponse;
  assessment: AssessmentOutput | null;
  shootingContext: string;
  proposedDays: number | undefined;
}

export async function generatePresentation(options: PresentationOptions): Promise<void> {
  const { projectName, breakdown, assessment, shootingContext, proposedDays } = options;

  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.title = `${projectName} - Production Breakdown`;
  pptx.author = 'Production Feasibility Engine';

  // ============================================
  // SLIDE 1: Title
  // ============================================
  const slide1 = pptx.addSlide();
  slide1.background = { color: COLORS.black };

  slide1.addText(projectName || 'Production Breakdown', {
    x: 0.5,
    y: 2.5,
    w: '90%',
    h: 1.2,
    fontSize: 48,
    bold: true,
    color: COLORS.cream,
    align: 'center',
  });

  slide1.addText('Production Feasibility Assessment', {
    x: 0.5,
    y: 3.8,
    w: '90%',
    h: 0.6,
    fontSize: 24,
    color: COLORS.gold,
    align: 'center',
  });

  slide1.addText(`Generated by Production Feasibility Engine`, {
    x: 0.5,
    y: 6.5,
    w: '90%',
    h: 0.4,
    fontSize: 12,
    color: COLORS.lightGray,
    align: 'center',
  });

  // ============================================
  // SLIDE 2: Executive Summary
  // ============================================
  if (assessment) {
    const slide2 = pptx.addSlide();
    addHeader(slide2, 'Executive Summary');

    const verdictColor = assessment.verdict === 'GREEN' ? COLORS.green :
                         assessment.verdict === 'AMBER' ? COLORS.amber : COLORS.red;

    // Verdict box
    slide2.addShape('rect', {
      x: 0.5,
      y: 1.5,
      w: 12.3,
      h: 1.2,
      fill: { color: verdictColor },
    });

    slide2.addText(
      assessment.verdict === 'GREEN' ? 'LOOKS ACHIEVABLE' :
      assessment.verdict === 'AMBER' ? 'PRESSURE POINTS IDENTIFIED' : 'SIGNIFICANT CHALLENGES',
      {
        x: 0.5,
        y: 1.6,
        w: 12.3,
        h: 0.5,
        fontSize: 24,
        bold: true,
        color: COLORS.white,
        align: 'center',
      }
    );

    slide2.addText(assessment.verdictReason, {
      x: 0.5,
      y: 2.15,
      w: 12.3,
      h: 0.5,
      fontSize: 14,
      color: COLORS.white,
      align: 'center',
    });

    // Key metrics
    const metrics = [
      { label: 'Recommended Days', value: assessment.recommendedShootDays.toString() },
      { label: 'Avg Shots/Day', value: assessment.avgShotsPerDay.toFixed(1) },
      { label: 'Production Scale', value: assessment.productionScale },
    ];

    metrics.forEach((metric, i) => {
      slide2.addShape('rect', {
        x: 0.5 + (i * 4.1),
        y: 3.0,
        w: 3.9,
        h: 1.2,
        fill: { color: COLORS.lightGray },
      });
      slide2.addText(metric.value, {
        x: 0.5 + (i * 4.1),
        y: 3.1,
        w: 3.9,
        h: 0.7,
        fontSize: 32,
        bold: true,
        color: COLORS.darkGray,
        align: 'center',
      });
      slide2.addText(metric.label, {
        x: 0.5 + (i * 4.1),
        y: 3.75,
        w: 3.9,
        h: 0.4,
        fontSize: 12,
        color: COLORS.darkGray,
        align: 'center',
      });
    });

    // Copy-ready summary
    slide2.addText('Summary:', {
      x: 0.5,
      y: 4.5,
      w: 12.3,
      h: 0.4,
      fontSize: 14,
      bold: true,
      color: COLORS.darkGray,
    });

    slide2.addText(assessment.copyReadySummary, {
      x: 0.5,
      y: 4.9,
      w: 12.3,
      h: 1.5,
      fontSize: 12,
      color: COLORS.darkGray,
      valign: 'top',
    });
  }

  // ============================================
  // SLIDE 3: Script Overview
  // ============================================
  if (breakdown.breakdown) {
    const slide3 = pptx.addSlide();
    addHeader(slide3, 'Script Overview');

    const bd = breakdown.breakdown;
    const rollup = bd.rollup;

    // Key stats
    const stats = [
      { label: 'Total Scenes', value: bd.totalScenes.toString() },
      { label: 'Unique Locations', value: bd.uniqueLocations.toString() },
      { label: 'Company Moves', value: bd.companyMoves.toString() },
      { label: 'Est. Shoot Days', value: rollup.estimatedShootDays.toString() },
      { label: 'Total Shots', value: rollup.totalEstimatedShots.toString() },
    ];

    stats.forEach((stat, i) => {
      slide3.addShape('rect', {
        x: 0.5 + (i * 2.46),
        y: 1.5,
        w: 2.3,
        h: 1.0,
        fill: { color: COLORS.lightGray },
      });
      slide3.addText(stat.value, {
        x: 0.5 + (i * 2.46),
        y: 1.55,
        w: 2.3,
        h: 0.55,
        fontSize: 28,
        bold: true,
        color: COLORS.darkGray,
        align: 'center',
      });
      slide3.addText(stat.label, {
        x: 0.5 + (i * 2.46),
        y: 2.1,
        w: 2.3,
        h: 0.35,
        fontSize: 10,
        color: COLORS.darkGray,
        align: 'center',
      });
    });

    // Complexity flags
    const flags = [];
    if (rollup.hasTechnicalShots) flags.push('Technical Shots');
    if (rollup.hasHeroProduct) flags.push('Hero Product');
    if (rollup.hasVFX) flags.push(`VFX (${rollup.vfxComplexity})`);

    if (flags.length > 0) {
      slide3.addText('Complexity Flags: ' + flags.join(' • '), {
        x: 0.5,
        y: 2.7,
        w: 12.3,
        h: 0.4,
        fontSize: 12,
        color: COLORS.amber,
        bold: true,
      });
    }

    // Schedule notes
    if (rollup.scheduleNotes && rollup.scheduleNotes.length > 0) {
      slide3.addText('Schedule Notes:', {
        x: 0.5,
        y: 3.2,
        w: 12.3,
        h: 0.3,
        fontSize: 12,
        bold: true,
        color: COLORS.darkGray,
      });

      const notesText = rollup.scheduleNotes.map(note => `• ${note}`).join('\n');
      slide3.addText(notesText, {
        x: 0.5,
        y: 3.5,
        w: 12.3,
        h: 2,
        fontSize: 11,
        color: COLORS.darkGray,
        valign: 'top',
      });
    }
  }

  // ============================================
  // SLIDE 4: Scene Breakdown Table
  // ============================================
  if (breakdown.breakdown && breakdown.breakdown.scenes.length > 0) {
    const slide4 = pptx.addSlide();
    addHeader(slide4, 'Scene Breakdown');

    const scenes = breakdown.breakdown.scenes;

    const tableData: PptxGenJS.TableRow[] = [
      // Header row
      [
        { text: '#', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
        { text: 'INT/EXT', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
        { text: 'Location', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
        { text: 'Description', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
        { text: 'Shots', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
        { text: 'Complexity', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
      ],
    ];

    scenes.slice(0, 10).forEach((scene, i) => {
      const complexity = [];
      if (scene.complexity.technicalComplexity) complexity.push('Tech');
      if (scene.complexity.productHeroMoment) complexity.push('Hero');
      if (scene.complexity.vfxSfxLevel !== 'none') complexity.push('VFX');

      tableData.push([
        { text: scene.sceneNumber.toString(), options: { align: 'center', fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
        { text: scene.intExt, options: { align: 'center', fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
        { text: scene.locationName.substring(0, 20), options: { fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
        { text: scene.description.substring(0, 40) + (scene.description.length > 40 ? '...' : ''), options: { fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
        { text: scene.schedule.estimatedShots.toString(), options: { align: 'center', fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
        { text: complexity.join(', ') || '-', options: { align: 'center', fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
      ]);
    });

    slide4.addTable(tableData, {
      x: 0.5,
      y: 1.5,
      w: 12.3,
      fontSize: 10,
      colW: [0.5, 0.8, 2, 4.5, 0.7, 1.2],
      border: { pt: 0.5, color: COLORS.lightGray },
    });

    if (scenes.length > 10) {
      slide4.addText(`+ ${scenes.length - 10} more scenes...`, {
        x: 0.5,
        y: 6.5,
        w: 12.3,
        h: 0.3,
        fontSize: 10,
        color: COLORS.darkGray,
        italic: true,
      });
    }
  }

  // ============================================
  // SLIDE 5: Talent Summary
  // ============================================
  if (breakdown.breakdown) {
    const slide5 = pptx.addSlide();
    addHeader(slide5, 'Talent Requirements');

    const rollup = breakdown.breakdown.rollup;

    const talentData: PptxGenJS.TableRow[] = [
      [
        { text: 'Role', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white } },
        { text: 'Count', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
        { text: 'Notes', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white } },
      ],
      [
        { text: 'Hero/Principal', options: { fill: { color: COLORS.white } } },
        { text: rollup.totalHeroPrincipal.toString(), options: { align: 'center', fill: { color: COLORS.white } } },
        { text: 'Named characters with significant action', options: { fill: { color: COLORS.white } } },
      ],
      [
        { text: 'Featured', options: { fill: { color: COLORS.lightGray } } },
        { text: rollup.totalFeatured.toString(), options: { align: 'center', fill: { color: COLORS.lightGray } } },
        { text: 'Recognizable, specific action, may have lines', options: { fill: { color: COLORS.lightGray } } },
      ],
      [
        { text: 'Walk-ons', options: { fill: { color: COLORS.white } } },
        { text: rollup.totalWalkOns.toString(), options: { align: 'center', fill: { color: COLORS.white } } },
        { text: 'Brief visible moments', options: { fill: { color: COLORS.white } } },
      ],
      [
        { text: 'Peak Extras', options: { fill: { color: COLORS.lightGray } } },
        { text: rollup.peakExtras.toString(), options: { align: 'center', fill: { color: COLORS.lightGray } } },
        { text: 'Maximum extras needed on any single day', options: { fill: { color: COLORS.lightGray } } },
      ],
    ];

    slide5.addTable(talentData, {
      x: 0.5,
      y: 1.5,
      w: 12.3,
      fontSize: 12,
      colW: [2.5, 1.5, 8.3],
      border: { pt: 0.5, color: COLORS.lightGray },
    });

    // Usage exposure if available
    if (assessment) {
      slide5.addText('Indicative Usage Exposure:', {
        x: 0.5,
        y: 4.0,
        w: 12.3,
        h: 0.4,
        fontSize: 14,
        bold: true,
        color: COLORS.darkGray,
      });

      slide5.addText(
        `£${assessment.usageExposureRange.min.toLocaleString()} - £${assessment.usageExposureRange.max.toLocaleString()}`,
        {
          x: 0.5,
          y: 4.4,
          w: 12.3,
          h: 0.5,
          fontSize: 20,
          color: COLORS.blue,
        }
      );
    }
  }

  // ============================================
  // SLIDE 6: Schedule Reality
  // ============================================
  if (assessment) {
    const slide6 = pptx.addSlide();
    addHeader(slide6, 'Schedule Assessment');

    // Proposed vs Recommended
    slide6.addShape('rect', {
      x: 0.5,
      y: 1.5,
      w: 5.9,
      h: 1.5,
      fill: { color: COLORS.amber },
    });
    slide6.addText('PROPOSED', {
      x: 0.5,
      y: 1.55,
      w: 5.9,
      h: 0.3,
      fontSize: 12,
      color: COLORS.white,
      align: 'center',
    });
    slide6.addText(proposedDays?.toString() || '?', {
      x: 0.5,
      y: 1.85,
      w: 5.9,
      h: 0.8,
      fontSize: 48,
      bold: true,
      color: COLORS.white,
      align: 'center',
    });
    slide6.addText('days', {
      x: 0.5,
      y: 2.65,
      w: 5.9,
      h: 0.3,
      fontSize: 14,
      color: COLORS.white,
      align: 'center',
    });

    slide6.addShape('rect', {
      x: 6.9,
      y: 1.5,
      w: 5.9,
      h: 1.5,
      fill: { color: COLORS.green },
    });
    slide6.addText('RECOMMENDED', {
      x: 6.9,
      y: 1.55,
      w: 5.9,
      h: 0.3,
      fontSize: 12,
      color: COLORS.white,
      align: 'center',
    });
    slide6.addText(assessment.recommendedShootDays.toString(), {
      x: 6.9,
      y: 1.85,
      w: 5.9,
      h: 0.8,
      fontSize: 48,
      bold: true,
      color: COLORS.white,
      align: 'center',
    });
    slide6.addText('days', {
      x: 6.9,
      y: 2.65,
      w: 5.9,
      h: 0.3,
      fontSize: 14,
      color: COLORS.white,
      align: 'center',
    });

    // High risk days
    if (assessment.highRiskDays.length > 0) {
      slide6.addText('High-Risk Days: ' + assessment.highRiskDays.join(', '), {
        x: 0.5,
        y: 3.3,
        w: 12.3,
        h: 0.4,
        fontSize: 12,
        color: COLORS.red,
        bold: true,
      });
    }

    // Company move pressure
    if (assessment.companyMovePressure.flagged) {
      slide6.addText('⚠️ ' + assessment.companyMovePressure.reason, {
        x: 0.5,
        y: 3.7,
        w: 12.3,
        h: 0.4,
        fontSize: 12,
        color: COLORS.amber,
      });
    }

    // Assumptions vs Reality
    if (assessment.assumptionsVsReality.length > 0) {
      slide6.addText('Assumptions vs Reality:', {
        x: 0.5,
        y: 4.2,
        w: 12.3,
        h: 0.4,
        fontSize: 14,
        bold: true,
        color: COLORS.darkGray,
      });

      const assumptionRows: PptxGenJS.TableRow[] = [
        [
          { text: 'Item', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white } },
          { text: 'Assumed', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
          { text: 'Reality', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
          { text: 'Status', options: { bold: true, fill: { color: COLORS.black }, color: COLORS.white, align: 'center' } },
        ],
      ];

      assessment.assumptionsVsReality.slice(0, 6).forEach((item, i) => {
        const statusColor = item.status === 'aligned' ? COLORS.green :
                           item.status === 'stretched' ? COLORS.amber : COLORS.red;
        assumptionRows.push([
          { text: item.label, options: { fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
          { text: item.assumed?.toString() || '-', options: { align: 'center', fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
          { text: item.reality.toString(), options: { align: 'center', fill: { color: i % 2 === 0 ? COLORS.white : COLORS.lightGray } } },
          { text: item.status.toUpperCase(), options: { align: 'center', fill: { color: statusColor }, color: COLORS.white, bold: true } },
        ]);
      });

      slide6.addTable(assumptionRows, {
        x: 0.5,
        y: 4.6,
        w: 12.3,
        fontSize: 10,
        colW: [4, 2, 2, 2],
        border: { pt: 0.5, color: COLORS.lightGray },
      });
    }
  }

  // ============================================
  // SLIDE 7: Budget Bands
  // ============================================
  if (assessment) {
    const slide7 = pptx.addSlide();
    addHeader(slide7, 'Budget Indication');

    slide7.addText('Production Budget Band:', {
      x: 0.5,
      y: 1.5,
      w: 12.3,
      h: 0.4,
      fontSize: 14,
      bold: true,
      color: COLORS.darkGray,
    });

    const prodMin = assessment.productionCost.totalProduction.lean;
    const prodMax = assessment.productionCost.totalProduction.ambitious;

    slide7.addShape('rect', {
      x: 0.5,
      y: 1.9,
      w: 12.3,
      h: 1.2,
      fill: { color: COLORS.lightGray },
    });

    slide7.addText(
      `£${prodMin.toLocaleString()} - £${prodMax.toLocaleString()}`,
      {
        x: 0.5,
        y: 2.0,
        w: 12.3,
        h: 0.7,
        fontSize: 36,
        bold: true,
        color: COLORS.darkGray,
        align: 'center',
      }
    );

    slide7.addText(
      `${assessment.recommendedShootDays} days × £${assessment.productionCost.costPerDay.lean.toLocaleString()}-${assessment.productionCost.costPerDay.ambitious.toLocaleString()}/day (${shootingContext})`,
      {
        x: 0.5,
        y: 2.7,
        w: 12.3,
        h: 0.4,
        fontSize: 12,
        color: COLORS.darkGray,
        align: 'center',
      }
    );

    // Post budget
    slide7.addText('Post-Production Minimum:', {
      x: 0.5,
      y: 3.5,
      w: 12.3,
      h: 0.4,
      fontSize: 14,
      bold: true,
      color: COLORS.darkGray,
    });

    slide7.addText(
      `£${assessment.postProduction.minimum.toLocaleString()} - £${assessment.postProduction.maximum.toLocaleString()}`,
      {
        x: 0.5,
        y: 3.9,
        w: 12.3,
        h: 0.5,
        fontSize: 24,
        color: COLORS.darkGray,
      }
    );

    if (assessment.postProduction.vfxAdjusted) {
      slide7.addText('* VFX-adjusted minimum applied', {
        x: 0.5,
        y: 4.4,
        w: 12.3,
        h: 0.3,
        fontSize: 10,
        color: COLORS.amber,
        italic: true,
      });
    }

    // Disclaimer
    slide7.addText('Note: These are indicative budget bands for early-stage planning only. Not a quote.', {
      x: 0.5,
      y: 6.5,
      w: 12.3,
      h: 0.3,
      fontSize: 10,
      color: COLORS.darkGray,
      italic: true,
    });
  }

  // ============================================
  // SLIDE 8: What to Challenge
  // ============================================
  if (assessment && assessment.whatToChallenge.length > 0) {
    const slide8 = pptx.addSlide();
    addHeader(slide8, 'What to Challenge First');

    assessment.whatToChallenge.forEach((item, i) => {
      slide8.addShape('ellipse', {
        x: 0.5,
        y: 1.5 + (i * 0.7),
        w: 0.4,
        h: 0.4,
        fill: { color: COLORS.blue },
      });

      slide8.addText((i + 1).toString(), {
        x: 0.5,
        y: 1.55 + (i * 0.7),
        w: 0.4,
        h: 0.35,
        fontSize: 14,
        bold: true,
        color: COLORS.white,
        align: 'center',
      });

      slide8.addText(item, {
        x: 1.1,
        y: 1.5 + (i * 0.7),
        w: 11.5,
        h: 0.5,
        fontSize: 14,
        color: COLORS.darkGray,
        valign: 'middle',
      });
    });
  }

  // ============================================
  // SLIDE 9: Warnings / PIBS
  // ============================================
  if (assessment && assessment.pibsWarnings.length > 0) {
    const slide9 = pptx.addSlide();
    addHeader(slide9, 'Client-Safety Warnings');

    assessment.pibsWarnings.forEach((warning, i) => {
      slide9.addShape('rect', {
        x: 0.5,
        y: 1.5 + (i * 0.8),
        w: 12.3,
        h: 0.7,
        fill: { color: 'FFE5E5' },
        line: { color: COLORS.red, pt: 1 },
      });

      slide9.addText('⚠️ ' + warning, {
        x: 0.7,
        y: 1.55 + (i * 0.8),
        w: 12,
        h: 0.6,
        fontSize: 12,
        color: COLORS.red,
        valign: 'middle',
      });
    });
  }

  // ============================================
  // SLIDE 10: End slide
  // ============================================
  const slideEnd = pptx.addSlide();
  slideEnd.background = { color: COLORS.black };

  slideEnd.addText('Questions?', {
    x: 0.5,
    y: 2.8,
    w: '90%',
    h: 1,
    fontSize: 48,
    bold: true,
    color: COLORS.cream,
    align: 'center',
  });

  slideEnd.addText('Generated by Production Feasibility Engine', {
    x: 0.5,
    y: 6.5,
    w: '90%',
    h: 0.4,
    fontSize: 12,
    color: COLORS.lightGray,
    align: 'center',
  });

  // ============================================
  // SAVE
  // ============================================
  const filename = `${projectName.replace(/[^a-zA-Z0-9]/g, '_')}_Production_Breakdown.pptx`;
  await pptx.writeFile({ fileName: filename });
}

// Helper function to add consistent header
function addHeader(slide: PptxGenJS.Slide, title: string): void {
  slide.addShape('rect', {
    x: 0,
    y: 0,
    w: '100%',
    h: 1.2,
    fill: { color: COLORS.black },
  });

  slide.addText(title, {
    x: 0.5,
    y: 0.35,
    w: 12.3,
    h: 0.6,
    fontSize: 28,
    bold: true,
    color: COLORS.white,
  });
}
